import { ProjectArchive } from "./definitions";

export const projectArchiveData: ProjectArchive[] = [
  {
    project: "Silent Hill: Ascension",
    madeAt: "Genvid Technologies",
    href: "https://genvid.com/titles/silent-hill-ascension",
    techStack: ["Typescript", "React", "Redux Toolkit"],
    year: "2023 - 2024",
  },
  {
    project: "PayloadCMS - Internal CMS for Managing Product Data",
    madeAt: "Genvid Technologies",
    href: "https://apps.shopify.com/teelaunch-1",
    techStack: [
      "Typescript",
      "React",
      "PayloadCMS",
      "Express",
      "Node",
      "MongoDB",
    ],
    year: "2023",
  },
  {
    project: "The Walking Dead Last Mile",
    madeAt: "Genvid Technologies",
    href: "https://genvid.com/titles/the-walking-dead-last-mile",
    techStack: ["Typescript", "React", "Context API"],
    year: "2022",
  },
  {
    project: "Brookyln Challenge",
    madeAt: "Github",
    href: "https://github.com/ebotsupreme/BrooklynChallenge",
    techStack: ["Typescript", "React Native"],
    year: "2021",
  },
  {
    project: "TeeLaunch",
    madeAt: "Sunrise Integraion",
    href: "https://apps.shopify.com/teelaunch-1",
    techStack: [
      "JavaScript",
      "JQuery",
      "React",
      "PHP",
      "Laravel",
      "MySQL",
      "Shopify",
    ],
    year: "2019 - 2021",
  },
  {
    project: "Pac Gourmet",
    madeAt: "Sunrise Integration",
    href: "https://www.pacgourmet.com",
    techStack: ["JavaScript", "CSS", "HTML", "PHP", "MySQL", "Shopify"],
    year: "2019",
  },
  {
    project: "Murphy Magic",
    madeAt: "Sunrise Integration",
    href: "https://shop.52kards.com",
    techStack: ["JavaScript", "CSS", "HTML", "PHP", "MySQL", "Shopify"],
    year: "2018",
  },
  {
    project: "McPeeks Dodge Anaheim Dealership",
    madeAt: "Pixel Motion",
    href: "https://www.mcpeeksdodgeanaheim.com",
    techStack: [
      "JavaScript",
      "TypeScript",
      "React",
      "Context API",
      "Redux Toolkit",
    ],
    year: "2017",
  },
  {
    project: "Landers Auto Dealership",
    madeAt: "Pixel Motion",
    href: "https://www.landers.com",
    techStack: [
      "JavaScript",
      "JQuery",
      "Html",
      "CSS",
      "Bootstrap",
      "Wordpress",
    ],
    year: "2016",
  },
];
